// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const fourMil = 4000000;

function EvenFibSum(): number {
    let accumulator = 0;
    let sumTerm = 0;

    let lastTerm = 1;
    let nextTerm = 2;

    while (sumTerm < fourMil) {
        sumTerm = nextTerm + lastTerm;
        if (sumTerm % 2 === 0) {
            accumulator += sumTerm;
        }
        lastTerm = nextTerm;
        nextTerm = sumTerm;
    }

    return accumulator;
}

// Outputs: 4613730
console.log(EvenFibSum())